export const en = {
	UnauthorizeLoginError: 'Login denied for user authorization level.',
	AverageReceiptAmount: 'Average Receipt Amount',
	SelectMall: 'Select Mall',
	VisitFrequency: 'Visit Frequency',
	VİSİTFREQUENCY: 'Visit Frequency',
	VISITFREQUENCY: 'Visit Frequency',
	District: 'District',
	DİSTRİCT: 'District',
	DISTRICT: 'District',
	IsStockAreAdded: 'stock are added?',
	SubStock: 'Subtract Stock',
	Sub: 'Subtract',
	Deactivate: 'Deactivate',
	Activate: 'Activate',
	Add: 'Add',
	AddStock: 'Add Stock',
	GiftProgress: 'Gift Progress',
	StockValue: 'Stock Value',
	AreYouSure: 'Are you sure?',
	CantBeEmpty: "Stock amount can't be empty!",
	Yes: 'Yes',
	No: 'No',
	Username: 'Username',
	Password: 'Password',
	MallCode: 'Mall Code',
	Login: 'Login',
	LogOff: 'Log Off',
	AreYouSureWantToLogOff: 'Are you sure want to log off?',
	RememberMe: 'Remember Me',
	Ok: 'Ok',
	OK: 'OK',
	CANCEL: 'CANCEL',
	Cancel: 'Cancel',
	CampaignDetails: 'Campaign Details',
	GetEMailReport: 'Get E-Mail Report',
	Cockpit: 'Cockpit',
	NumberOfNewMembers: '# of New Members',
	NumberOfShoppers: '# of Shoppers',
	NumberOfReceipts: '# of Receipts',
	TotalRecordedReceiptAmount: 'Total Recorded Receipt Amount',
	NumberOfCoupons: '# of Coupons',
	NumberOfMembersWithCoupon: '# of Members Who Take Coupon',
	StartDate: 'Start Date',
	EndDate: 'End Date',
	ReceipentEMails: 'Receipent E-Mails',
	CompareReceipentEMails: 'Receipent E-Mails',
	GetReport: 'Get Report',
	InputFieldEmptyError: 'Try again after fill required field.',
	InputFieldIncorrectError: 'Incorrect username or password.',
	MultipleLoginError:
		'You are already logged in from another device. Please log off first. Contact: info@omegabigdata.com',
	Error: 'Error',
	Warning: 'Warning',
	Success: 'Success Operation',
	TakeRequest: 'Request has been taken. \nThe report will be sent as soon as possible.',
	InvalidMailAdress: 'Invalid e-mail address. \nCheck the e-mail address and try again.',
	InvalidMailAdressInThere: 'Invalid e-mail adress',
	MailAdressNotNull: 'E-mail adress can not null!',
	TotalSpending: 'Total Spending',
	TotalNumberOfMember: 'Total # of Member',
	AverageSpending: 'Average Spending',
	PercentOfMember: 'Percent Of Member',
	PercentOfAmount: 'Percent Of Amount',
	NumberOfReceipt: '# of Receipt',
	AverageAmountOfReceipt: 'Average Amount Of Receipt',
	SortCriteria: 'Sort Criteria',
	StoreName: 'Store Name',
	BestOf: 'Best Of',
	STORE: 'Store',
	GENDER: 'Gender',
	AGEINTERVAL: 'Age Interval',
	AgeInterval: 'Age Interval',
	CITY: 'City',
	CİTY: 'City',
	COUNTY: 'County',
	County: 'Counties',
	HOUR: 'Hour',
	Hour: 'Hours',
	Minute: 'Minute',
	DAY: 'Day',
	Male: 'Male',
	Female: 'Female',
	Gender: 'Gender',
	StartDateBigerThanEndDateError: 'Start date can not bigger than end date.',
	ServiceError: 'An error occured in system. Try again later.',
	TotalNumberOfMembers: 'Total # of Members',
	ReceiptAmountPerMember: 'Receipt Amount Per Member',
	TotalNumberOfRevokedCoupons: 'Total # of Revoked Coupons',
	TotalNumberOfPeople: 'Total # of People',
	NumberOfMembers: '# of Members',
	AverageReceiptSpending: 'Average Receipt Spending',
	TotalReceiptAmountPerMember: 'Total Receipt Amount Per Member',
	MONDAY: 'MONDAY',
	TUESDAY: 'TUESDAY',
	WEDNESDAY: 'WEDNESDAY',
	THURSDAY: 'THURSDAY',
	FRIDAY: 'FRIDAY',
	SATURDAY: 'SATURDAY',
	SUNDAY: 'SUNDAY',
	Monday: 'Monday',
	Tuesday: 'Tuesday',
	Wednesday: 'Wednesday',
	Thursday: 'Thursday',
	Friday: 'Friday',
	Saturday: 'Saturday',
	Sunday: 'Sunday',
	Mon: 'Mon',
	Tue: 'Tue',
	Wed: 'Wed',
	Thu: 'Thu',
	Fri: 'Fri',
	Sat: 'Sat',
	Sun: 'Sun',
	Day: 'Day',
	NoRecordedAtSpecifiedDates: 'Can not found record at specified dates!',
	ServiceUnreachableError: 'Can not reach Omega Big Data servers. Check connections and try again.',
	ReportsDateInterval: 'Reports Date Interval',
	DatesIncludeReports: 'Start date and end date are included in the reports.',
	Filter: 'Filter',
	LogOffSession: 'Log Off Session',
	CampaignDates: 'Campaign Dates',
	DateSelection: 'Date Selection',
	SelectedDate: 'Selected Date',
	Yesterday: 'Yesterday',
	LastWeek: 'Last Week',
	LastMonth: 'Last Month',
	PreviousDay: 'Previous Day',
	Live: 'Live',
	SelectDate: 'Select Date',
	LIVE: 'LIVE',
	InReportDates: 'In Report Dates',
	InCampaignDates: 'In Campaign Dates',
	Selection: 'Sorting Criteria',
	Processing: 'Processing...',
	'ContactUsinfo@omegabigdata.com': 'Contact us to renew password.\ninfo@omegabigdata.com',
	ForgotPassword: 'Forgot password',
	PasswordRenew: 'Password Renew',
	ActualStock: 'Actual Stock',
	TodayGivenStock: 'Today Given',
	TotalGivenStock: 'Total Given',
	Passive: 'Passive',
	NoRecorded: 'Can not found active campaign!',
	NoGiftAtSpecifiedCampaign: 'Can not found gift at selected campaign!',
	GiftStock: 'Gift Stock',
	AnErrorOccuredPleaseTryAgainLater: 'An Error Occured Please Try Again Later!',
	IsGiftMadePassive: 'Is gift made passive?',
	IsGiftMadeActive: 'Is gift made active?',
	MakePassive: 'Make Passive',
	MakeActive: 'Make Active',
	IsStockAreSubstracted: 'stock are subtracted?',
	LAST3MONTH: 'LAST 3 MONTHS',
	LAST6MONTH: 'LAST 6 MONTHS',
	LAST12MONTH: 'LAST 12 MONTHS',
	Quantitiy: 'quantity',
	Person: 'person',
	person: 'person',
	ReceiptAmounts: 'Receipt Amount',
	ManagerSummary: 'Manager Summary',
	TotalNumberOfMaleMember: 'Total # of Male Member',
	TotalNumberOfFemaleMember: 'Total # of Female Member',
	MemberActivityInfo: 'Member Activity Info',
	ProcessedMemberInLast3Months: 'Members Who Take Action In Last 3 Months ',
	ProcessedMemberInLast6Months: 'Members Who Take Action In Last 6 Months ',
	ProcessedMemberInLast12Months: 'Members Who Take Action In Last 12 Months ',
	NotProcessedMemberInLast12Months: "Members Who Didn't Take Action In Last 12 Months ",
	TotalNumberOfCustomers: 'Number Of Members',
	ALLTİME: 'ALL TIME',
	TryAgain: 'Try Again',
	Top3CountiesByTheTotalSpendingAmount: 'Top 5 Counties By The Total Spending Amount',
	Top3StoresByTheTotalReceiptAmount: 'Top 3 Stores By The Total Receipt Amount',
	Top3StoresByTheTotalReceiptCount: 'Top 3 Stores By The Total Receipt Count',
	PercentOfSpending: 'Percent Of Spending',
	CompareMethod: 'Compare Method',
	CompareCampaign: 'Compare Campaign',
	CompareDate: 'Compare Date',
	FirstCampaign: 'First Campaign',
	SecondCampaign: 'Second Campaign',
	Compare: 'Compare',
	GetExcelReport: 'Get Excel Report',
	FirstPeriodStartDate: 'First Period Start Date',
	FirstPeriodEndDate: 'First Period End Date',
	SecondPeriodStartDate: 'Second Period Start Date',
	SecondPeriodEndDate: 'Second Period End Date',
	GeneralSummary: 'General Summary',
	TotalCouponNumber: 'Total Coupon Number',
	NumberOfMembersWhoTakeAction: '# Of Member Who Take Action',
	PercentOfMale: 'Percent Of Male',
	PercentOfFemale: 'Percent Of Female',
	NumberOfNewMember: '# Of New Member',
	RecordedTotalSpending: 'Recorded Total Spending',
	AverageSpendingPerMember: 'Average Spending Per Member',
	FirstPeriod: 'Period 1',
	SecondPeriod: 'Period 2',
	'ShopTotalSpending(First5)': 'Shop Total Spending (First 5)',
	InvalidDateIntervalOrCampaigns: 'Invalid date interval or campaign!',
	NoCampaignFounded: 'No campaign founded!',
	LoadingCampaigns: 'Loading campaigns...',
	CampaignsLoadingTryAgainLater: 'Campaigns loading, try again later!',
	'ShopNumberOfMember(First5)': 'Shop # Of Member (First 5)',
	'TotalCountySpending(First5)': 'County Total Spending (First 5)',
	'DistrictTotalSpending(First5)': 'District Total Spending (First 5)',
	NumberOfVisitPerMember: '# Of Visit Per Member',
	NumberOfReceiptPerMember: '# Of Receipt Per Member',
	NumberOfDifferentStore: '# Of Different Store',
	Sector: 'Sector',
	SECTOR: 'Sectors',
	TotalNumberOfReceipts: '# Of Receipts',
	NumberOfVisits: '# Of Visits',
	people: 'people',
	ReportValuePyramid: 'Member Value Pyramid',
	AllTime: 'All Time',
	CampaignsLoading: 'Campaigns loading...',
	TodayDeliverable: 'Today Deliverable',
	ManageQuotas: 'Manage Quotas',
	PerMember: 'Per Member',
	PerGlobal: 'Per Global',
	None: 'None',
	Daily: 'Daily',
	Weekly: 'Weekly',
	Monthly: 'Monthly',
	OnePeriod: 'One Period',
	Save: 'Save',
	NoQuotaFounded: 'No quota founded!',
	GiftQuotaManagement: 'Quota Management',
	QuotaDate: 'Quota Date',
	NoQuotaFound: 'No quota found!',
	Quota: 'Quota',
	Remain: 'Remain'
};
