export const fr = {
	UnauthorizeLoginError: "Avec ce compte d'utilisateur, vous ne pouvez pas vous connecter à l'application mobile",
	AverageReceiptAmount: 'Montant moyen du ticket de caisse',
	Activate: 'Activer',
	ActualStock: 'Stock effectif',
	Add: 'Ajouter',
	AddStock: 'Ajouter au stock',
	AGEINTERVAL: 'Tranche dge',
	AgeInterval: 'Tranche dge',
	ALLTIME: 'TOUT LE TEMPS',
	AllTime: 'Tout le temps',
	AnErrorOccuredPleaseTryAgainLater: 'Une erreur sest produite. Veuillez ressayer ultrieurement!',
	AreYouSure: 'tes-vous certain?',
	AreYouSureWantToLogOff: 'tes-vous certain de vouloir vous dconnecter?',
	AverageAmountOfReceipt: 'Montant moyen du ticket de caisse',
	AverageReceiptSpending: 'Montant moyen du ticket de caisse',
	AverageSpending: 'Dpenses moyennes',
	AverageSpendingPerMember: 'Dpenses moyennes par membre',
	BestOf: 'Meilleur(e)s',
	CampaignDates: 'Dates de campagne',
	CampaignDetails: 'Dtails de la campagne',
	CampaignsLoading: 'Chargement des campagnes...',
	CampaignsLoadingTryAgainLater: 'Chargement des campagnes',
	CANCEL: 'ANNULER',
	Cancel: 'Annuler',
	CantBeEmpty: 'La valeur du stock ne peut pas tre vide!',
	CITY: 'Villes',
	CTY: 'Villes',
	City: 'Ville',
	Cockpit: 'Tableau de bord',
	Compare: 'Comparer',
	CompareCampaign: 'Comparer les campagnes',
	CompareDate: 'Comparer les dates',
	CompareMethod: 'Comparer la mthode',
	CompareReceipentEMails: 'Adresses e-mail des destinataires',
	'ContactUsinfo@omegabigdata.com': 'Nous contacter pour changer de mot de passe',
	County: 'Dpartement',
	COUNTY: 'Dpartements',
	Daily: 'Quotidien',
	DateSelection: 'Slection de date',
	DatesIncludeReports: 'La date de dbut et la date de fin sont mentionnes dans les rapports.',
	DAY: 'Jours',
	Day: 'Jour',
	Deactivate: 'Dsactiver',
	DISTRICT: 'Rgion',
	District: 'Rgion',
	DSTRCT: 'Rgion',
	'DistrictTotalSpending(First5)': 'Dpenses totales par rgion (5 premires)',
	EndDate: 'Date de fin',
	Error: 'Erreur',
	Female: 'Fminin',
	FEMALE: 'Fminin',
	Filter: 'Filtre',
	FirstCampaign: 'Premire campagne',
	FirstPeriod: 'Priode 1',
	FirstPeriodEndDate: 'Date de fin de la premire priode',
	FirstPeriodStartDate: 'Date de dbut de la premire priode',
	ForgotPassword: 'Mot de passe oubli',
	Fri: 'Ven',
	Friday: 'Vendredi',
	GENDER: 'Sexe',
	Gender: 'Sexe',
	GeneralSummary: 'Rcapitulatif gnral',
	GetEMailReport: 'Obtenir un rapport par e-mail',
	GetExcelReport: 'Obtenir un rapport Excel',
	GetReport: 'Obtenir un rapport',
	GiftProgress: 'Avancement du cadeau',
	GiftQuotaManagement: 'Gestion des quotas',
	GiftStock: 'Stock de cadeaux',
	Hour: 'Heure',
	HOUR: 'Heures',
	InCampaignDates: 'Dans les dates de campagne',
	InputFieldEmptyError: 'Ressayez aprs avoir renseign le champ requis.',
	InputFieldIncorrectError: 'Nom dutilisateur ou mot de passe incorrect.',
	InReportDates: 'Dans les dates de rapport',
	InvalidDateIntervalOrCampaigns: 'Intervalle de dates ou campagne invalide!',
	InvalidMailAdress: 'Adresse e-mail invalide',
	InvalidMailAdressInThere: 'Adresse e-mail invalide',
	IsGiftMadeActive: 'Le cadeau a-t-il t rendu actif?',
	IsGiftMadePassive: 'Le cadeau a-t-il t rendu passif?',
	IsStockAreAdded: 'Ajout au stock?',
	IsStockAreSubstracted: 'Soustraction du stock?',
	LAST12MONTH: 'LES 12 DERNIERS MOIS',
	LAST3MONTH: 'LES 3 DERNIERS MOIS',
	LAST6MONTH: 'LES 6 DERNIERS MOIS',
	LastMonth: 'Le mois dernier',
	LastWeek: 'La semaine dernire',
	LIVE: 'EN DIRECT',
	Live: 'En direct',
	LoadingCampaigns: 'Chargement des campagnes...',
	Login: 'Connexion',
	LogOff: 'Dconnexion',
	LogOffSession: 'Fermer la session',
	MailAdressNotNull: 'Ladresse e-mail ne peut pas tre vide!',
	MakeActive: 'Rendre actif',
	MakePassive: 'Rendre passif',
	Male: 'Masculin',
	MallCode: 'Code du centre commercial',
	ManageQuotas: 'Grer les quotas',
	ManagerSummary: 'Rcapitulatif',
	MemberActivityInfo: 'Infos sur lactivit des membres',
	Minute: 'Minute',
	Mon: 'Lun',
	Monday: 'LUNDI',
	Monthly: 'Mensuel',
	MultipleLoginError:
		'Vous tes dj connect  partir dun autre terminal. Veuillez dabord vous dconnecter. Contact: info@omegabigdata.com',
	No: 'Non',
	NoCampaignFounded: 'Aucune campagne trouve!',
	NoGiftAtSpecifiedCampaign: 'Impossible de trouver de cadeau pour la campagne slectionne!',
	None: 'Aucun(e)',
	NoQuotaFound: 'Aucun quota trouv!',
	NoQuotaFounded: 'Aucun quota trouv!',
	NoRecorded: 'Impossible de trouver une campagne active!',
	NoRecordedAtSpecifiedDates: 'Impossible de trouver un enregistrement aux dates spcifies!',
	NotProcessedMemberInLast12Months: 'Membres qui nont pas t actifs dans les 12 derniers mois',
	NumberOfCoupons: 'Nb de bons de rduction',
	NumberOfDifferentStore: 'Nb de magasins diffrents',
	NumberOfMembers: 'Nb de membres',
	NumberOfMembersWhoTakeAction: 'Nb de membres actifs',
	NumberOfMembersWithCoupon: 'Nb de membres qui prennent des bons de rduction',
	NumberOfNewMember: 'Nb de nouveaux membres',
	NumberOfNewMembers: 'Nb de nouveaux membres',
	NumberOfReceipt: 'Nb de tickets de caisse',
	NumberOfReceiptPerMember: 'Nb de tickets de caisse par membre',
	NumberOfReceipts: 'Nb de tickets de caisse',
	NumberOfShoppers: 'Nb dacheteurs',
	NumberOfVisitPerMember: 'Nb de visites par membre',
	NumberOfVisits: 'Nb de visites',
	Ok: 'Ok',
	OK: 'OK',
	OnePeriod: 'Une priode',
	Passive: 'Passif',
	Password: 'Mot de passe',
	PasswordRenew: 'Changement de mot de passe',
	people: 'personnes',
	PercentOfAmount: 'Pourcentage du montant',
	PercentOfFemale: 'Pourcentage de femmes',
	PercentOfMale: 'Pourcentage dhommes',
	PercentOfMember: 'Pourcentage de membres',
	PercentOfSpending: 'Pourcentage des dpenses',
	PerGlobal: 'Globalement',
	PerMember: 'Par membre',
	Person: 'personne',
	person: 'personne',
	PreviousDay: 'Jour prcdent',
	ProcessedMemberInLast12Months: 'Membres qui ont t actifs dans les 12 derniers mois',
	ProcessedMemberInLast3Months: 'Membres qui ont t actifs dans les 3 derniers mois',
	ProcessedMemberInLast6Months: 'Membres qui ont t actifs dans les 6 derniers mois',
	Processing: 'Traitement en cours...',
	Quantity: 'quantit',
	Quota: 'Quota',
	QuotaDate: 'Date de quota',
	ReceipentEMails: 'Adresses e-mail des destinataires',
	ReceiptAmountPerMember: 'Montant du ticket de caisse par membre',
	ReceiptAmounts: 'Montant du ticket de caisse',
	RecordedTotalSpending: 'Dpenses totales enregistres',
	Remain: 'Conserver',
	RememberMe: 'Se souvenir de moi',
	ReportsDateInterval: 'Intervalle de dates des rapports',
	ReportValuePyramid: 'Pyramide de valeur des membres',
	Sat: 'Sam',
	Saturday: 'Samedi',
	Save: 'Enregistrer',
	SecondCampaign: 'Deuxime campagne',
	SecondPeriod: 'Priode 2',
	SecondPeriodEndDate: 'Date de fin de la deuxime priode',
	SecondPeriodStartDate: 'Date de dbut de la deuxime priode',
	Sector: 'Secteur',
	SECTOR: 'Secteurs',
	SelectDate: 'Slectionner une date',
	SelectedDate: 'Date slectionne',
	Selection: 'Critres de tri',
	SelectMall: 'Slectionner un centre commercial',
	ServiceError: 'Une erreur sest produite dans le systme. Ressayez ultrieurement.',
	ServiceUnreachableError: 'Impossible daccder aux serveurs. Vrifiez les connexions et ressayez.',
	'ShopNumberOfMember(First5)': 'Nb de boutiques des membres (5 premiers)',
	'ShopTotalSpending(First5)': 'Dpenses totales des boutiques (5 premires)',
	SortCriteria: 'Critres de tri',
	StartDate: 'Date de dbut',
	StartDateBigerThanEndDateError: 'La date de dbut ne peut pas tre postrieure  la date de fin.',
	StockValue: 'Valeur du stock',
	STORE: 'Magasin',
	StoreName: 'Nom du magasin',
	Sub: 'Soustraire',
	SubStock: 'Soustraire du stock',
	Success: 'Opration russie',
	Sun: 'Dim',
	Sunday: 'Dimanche',
	TakeRequest: 'La demande a t prise en compte. \nLe rapport sera envoy ds que possible.',
	Thu: 'Jeu',
	Thursday: 'Jeudi',
	TodayDeliverable: 'Livrable aujourdhui',
	TodayGivenStock: 'Distribu aujourdhui',
	Top3CountiesByTheTotalSpendingAmount: 'Top 5 des dpartements par montant total des dpenses',
	Top3StoresByTheTotalReceiptAmount: 'Top 3 des magasins par montant total des tickets de caisse',
	Top3StoresByTheTotalReceiptCount: 'Top 3 des magasins par nombre total de tickets de caisse',
	'TotalCountySpending(First5)': 'Dpenses totales par dpartement (5 premiers)',
	TotalCouponNumber: 'Nombre total de bons de rduction',
	TotalGivenStock: 'Total distribu',
	TotalNumberOfCustomers: 'Nombre de membres',
	TotalNumberOfFemaleMember: 'Nb total de membres fminins',
	TotalNumberOfMaleMember: 'Nb total de membres masculins',
	TotalNumberOfMember: 'Nb total de membres',
	TotalNumberOfMembers: 'Nb total de membres',
	TotalNumberOfPeople: 'Nb total de personnes',
	TotalNumberOfReceipts: 'Nb de tickets de caisse',
	TotalNumberOfRevokedCoupons: 'Nb total de bons de rduction annuls',
	TotalReceiptAmountPerMember: 'Montant total des tickets de caisse par membre',
	TotalRecordedReceiptAmount: 'Montant total des tickets de caisse enregistrs',
	TotalSpending: 'Dpenses totales',
	TryAgain: 'Ressayer',
	Tue: 'Mar',
	Tuesday: 'Mardi',
	Username: 'Nom dutilisateur',
	VISITFREQUENCY: 'Frquence de visite',
	VisitFrequency: 'Frquence de visite',
	VSTFREQUENCY: 'Frquence de visite',
	Warning: 'Alerte',
	Wed: 'Mer',
	Wednesday: 'Mercredi',
	Weekly: 'Hebdomadaire',
	Yes: 'Oui',
	Yesterday: 'Hier'
};
