export const ru = {
	UnauthorizeLoginError: 'С уровнем доступа данного пользователя вход в мобильное приложение невозможен.',
	AverageReceiptAmount: 'Cредняя Cумма Kвитанции',
	Activate: 'Активировать',
	ActualStock: 'Всего подарков',
	Add: 'Добавить',
	AddStock: 'Добавить в наличие',
	AGEINTERVAL: 'Возрастной интервал',
	AgeInterval: 'Возрастной интервал',
	ALLTİME: 'За все время',
	AllTime: 'ЗА ВСЕ ВРЕМЯ',
	AnErrorOccuredPleaseTryAgainLater: 'Произошла ошибка. Пожалуйста, повторите попытку позже!',
	AreYouSure: 'Вы уверены?',
	AreYouSureWantToLogOff: 'Вы действительно хотите выйти из системы?',
	AverageAmountOfReceipt: 'Средняя сумма чека',
	AverageReceiptSpending: 'Средняя сумма чека',
	AverageSpending: 'Средние расходы',
	AverageSpendingPerMember: 'Средние расходы на одного участника',
	BestOf: 'Лучшие из ',
	CampaignDates: 'Даты проведения кампании',
	CampaignDetails: 'Сведения о кампании',
	CampaignsLoading: 'Загрузка кампаний ...',
	CampaignsLoadingTryAgainLater: 'Загрузка кампаний ...',
	CANCEL: 'ОТМЕНА',
	Cancel: 'Отмена',
	CantBeEmpty: 'Сумма подарков не может быть пуста!',
	CITY: 'Города',
	CİTY: 'Города',
	City: 'Город',
	Cockpit: 'Кокпит',
	Compare: 'Сравнить',
	CompareCampaign: 'Сравнить кампании',
	CompareDate: 'Сравнить даты',
	CompareMethod: 'Метод сравнения',
	CompareReceipentEMails: 'E-mail',
	'ContactUsinfo@omegabigdata.com': 'Свяжитесь с нами, чтобы обновить пароль',
	COUNTY: 'Район',
	County: 'Район',
	Daily: 'Ежедневно',
	DateSelection: 'Выбор даты',
	DatesIncludeReports: 'Дата начала и дата окончания включены в отчеты.',
	DAY: 'Дни',
	Day: 'День',
	Deactivate: 'Деактивировать',
	DISTRICT: 'Yлица',
	District: 'Yлица',
	DİSTRİCT: 'Yлица',
	'DistrictTotalSpending(First5)': 'Общая сумма расходов на округ (первые 5)',
	EndDate: 'Дата окончания',
	Error: 'Ошибка',
	Female: 'Женщина',
	FEMALE: 'Женщина',
	Filter: 'Фильтр',
	FirstCampaign: 'Первая кампания',
	FirstPeriod: 'Период 1',
	FirstPeriodEndDate: 'Дата окончания первого периода',
	FirstPeriodStartDate: 'Дата начала первого периода',
	ForgotPassword: 'Не помню пароль',
	FRIDAY: 'Пятница',
	Fri: 'Пт',
	Friday: 'Пятница',
	GENDER: 'Пол',
	Gender: 'Пол',
	GeneralSummary: 'Общие сведения о кампании',
	GetEMailReport: 'Получить отчет',
	GetExcelReport: 'Отчет в Excel',
	GetReport: 'Получить отчет на e-mail',
	GiftProgress: 'Процедура подарков',
	GiftQuotaManagement: 'Управление квотами',
	GiftStock: 'Подарки',
	HOUR: 'Часы',
	Hour: 'Часы',
	InCampaignDates: 'На период кампании',
	InputFieldEmptyError: 'Повторите попытку после заполнения поля.',
	InputFieldIncorrectError: 'Неверное имя пользователя или пароль.',
	InReportDates: 'На период отчета',
	InvalidDateIntervalOrCampaigns: 'Недействительный интервал дат или кампания!',
	InvalidMailAdress: 'Неверный адрес электронной почты. \nПроверьте адрес электронной почты и повторите попытку.',
	InvalidMailAdressInThere: 'Неверный адрес электронной почты',
	IsGiftMadeActive: 'Активен ли подарок?',
	IsGiftMadePassive: 'Является ли подарок пассивным?',
	IsStockAreAdded: 'добавлен ли подарок?',
	IsStockAreSubstracted: 'убрать из наличия?',
	LAST12MONTH: 'ПОСЛЕДНИЕ 12 МЕСЯЦЕВ',
	LAST3MONTH: 'ПОСЛЕДНИЕ 3 МЕСЯЦА',
	LAST6MONTH: 'ПОСЛЕДНИЕ 6 МЕСЯЦЕВ',
	LastMonth: 'Последний месяц',
	LastWeek: 'Последняя неделя',
	LIVE: 'НА ТЕКУЩУЮ ДАТУ',
	Live: 'На текущую дату',
	LoadingCampaigns: 'Загрузка кампании ...',
	Login: 'Авторизоваться',
	LogOff: 'Выход из системы',
	LogOffSession: 'Выход из системы',
	MailAdressNotNull: 'Адрес электронной почты не может быть пустым!',
	MakeActive: 'Сделать активным',
	MakePassive: 'Сделать пассивным',
	Male: 'Мужчина',
	MALE: 'Мужчина',
	MallCode: 'Код торгового центра',
	ManageQuotas: 'Управление квотами',
	ManagerSummary: 'Сведения о молле',
	MemberActivityInfo: 'Информация о деятельности участника',
	Minute: 'Минута',
	Mon: 'Пн',
	MONDAY: 'Понедельник',
	Monday: 'Понедельник',
	Monthly: 'Ежемесячно',
	MultipleLoginError:
		'Вы уже вошли в систему с другого устройства. Сначала выйдите из системы. Контактное лицо: info@omegabigdata.com',
	No: 'Нет',
	NoCampaignFounded: 'Не найдено ни одной кампании!',
	NoGiftAtSpecifiedCampaign: 'Не удалось найти подарок в выбранной кампании!',
	None: 'Не определено',
	NoQuotaFound: 'Квота не найдена!',
	NoQuotaFounded: 'Не найдена ни одна квота!',
	NoRecorded: 'Не удалось найти активную кампанию!',
	NoRecordedAtSpecifiedDates: 'Не удалось найти запись в указанные даты!',
	NotProcessedMemberInLast12Months: 'Участники, которые не совершали никаких действий за последние 12 месяцев',
	NumberOfCoupons: '# Купонов',
	NumberOfDifferentStore: '# Разных магазинов',
	NumberOfMembers: '# Участников',
	NumberOfMembersWhoTakeAction: '# Зарегистрированных участников, не получивших купоны',
	NumberOfMembersWithCoupon: '# Участников, получивших купоны',
	NumberOfNewMember: '# Новых участников',
	NumberOfNewMembers: '# Новых участников',
	NumberOfReceipt: '# Чеков',
	NumberOfReceiptPerMember: '# Чеков на участника',
	NumberOfReceipts: '# Чеков',
	NumberOfShoppers: '# Покупателей',
	NumberOfVisitPerMember: '# Посещений на участника',
	NumberOfVisits: '#  Посещений',
	Ok: 'Ок',
	OK: 'ОК',
	OnePeriod: 'Один период',
	Passive: 'Пассивный',
	Password: 'Пароль',
	PasswordRenew: 'Обновить пароль',
	people: 'чел',
	PercentOfAmount: 'Процент суммы',
	PercentOfFemale: 'Процент женщин',
	PercentOfMale: 'Процент мужчин',
	PercentOfMember: 'Процент участников',
	PercentOfSpending: 'Процент расходов',
	PerGlobal: 'В общем',
	PerMember: 'На участника',
	Person: 'человек',
	person: 'человек',
	PreviousDay: 'Предыдущий день',
	ProcessedMemberInLast12Months: 'Участники, которые активны за последние 12 месяцев',
	ProcessedMemberInLast3Months: 'Участники, которые активны за последние 3 месяца',
	ProcessedMemberInLast6Months: 'Участники, которые активны за последние 6 месяцев',
	Processing: 'Обработка ...',
	Quantitiy: 'количество',
	Quota: 'квота',
	QuotaDate: 'Дата квоты',
	ReceipentEMails: 'E-mail',
	ReceiptAmountPerMember: 'Сумма чека на человека',
	ReceiptAmounts: 'Сумма чека',
	RecordedTotalSpending: 'Общие расходы',
	Remain: 'Остаться',
	RememberMe: 'Запомнить меня',
	ReportsDateInterval: 'Диапазон дат отчета',
	ReportValuePyramid: 'Пирамида участников',
	Sat: 'Сб',
	SATURDAY: 'Суббота',
	Saturday: 'Суббота',
	Save: 'Сохранить',
	SecondCampaign: 'Вторая кампания',
	SecondPeriod: 'Период 2',
	SecondPeriodEndDate: 'Дата окончания второго периода',
	SecondPeriodStartDate: 'Дата начала второго периода',
	Sector: 'Сектор',
	SECTOR: 'Секторы',
	SelectDate: 'Выберите дату',
	SelectedDate: 'Выбранная дата',
	Selection: 'Критерии сортировки',
	SelectMall: 'Выберите Молл',
	ServiceError: 'В системе произошла ошибка. Попробуйте позже.',
	ServiceUnreachableError: 'Не удается связаться с серверами. Проверьте соединения и повторите попытку.',
	'ShopNumberOfMember(First5)': ' # участников по магазинам (первые 5)',
	'ShopTotalSpending(First5)': 'Общий объем покупок (первые 5)',
	SortCriteria: 'Критерии сортировки',
	StartDate: 'Дата начала',
	StartDateBigerThanEndDateError: 'Дата начала не может быть позже даты окончания.',
	StockValue: 'Стоимость подарков',
	STORE: 'Магазин',
	StoreName: 'Название магазина',
	Sub: 'Убрать',
	SubStock: 'Убрать из наличия',
	Success: 'Успешная операция',
	Sun: 'Вс',
	SUNDAY: 'Воскресенье',
	Sunday: 'Воскресенье',
	TakeRequest: 'Запрос был выполнен. \nОтчет будет отправлен как можно скорее.',
	Thu: 'Чт',
	THURSDAY: 'Четверг',
	Thursday: 'Четверг',
	TodayDeliverable: 'Квота на сегодня',
	TodayGivenStock: 'Сегодня выдан',
	Top3CountiesByTheTotalSpendingAmount: 'Топ-5 районов по общей сумме расходов',
	Top3StoresByTheTotalReceiptAmount: 'Топ-3 магазинов по общей сумме чеков',
	Top3StoresByTheTotalReceiptCount: 'Топ-3 магазинов по количеству чеков',
	'TotalCountySpending(First5)': 'Общие расходы района (первые 5)',
	TotalCouponNumber: 'Всего купонных номеров',
	TotalGivenStock: 'Всего выдано',
	TotalNumberOfCustomers: 'Количество участников',
	TotalNumberOfFemaleMember: 'Общее # женщин',
	TotalNumberOfMaleMember: 'Общее # мужчин',
	TotalNumberOfMember: 'Общее # участников',
	TotalNumberOfMembers: 'Общее # участников',
	TotalNumberOfPeople: 'Общее # человек',
	TotalNumberOfReceipts: '# Чеков',
	TotalNumberOfRevokedCoupons: 'Общее #  отмененных купонов',
	TotalReceiptAmountPerMember: 'Общая сумма чеков на одного участника',
	TotalRecordedReceiptAmount: 'Общая сумма чеков',
	TotalSpending: 'Общие расходы',
	TryAgain: 'Попробуйте еще раз',
	Tue: 'Вт',
	TUESDAY: 'Вторник',
	Tuesday: 'Вторник',
	Username: 'Имя пользователя',
	VISITFREQUENCY: 'Частота посещения',
	VisitFrequency: 'Частота посещения',
	VİSİTFREQUENCY: 'Частота посещения',
	Warning: 'Предупреждение',
	Wed: 'Ср',
	WEDNESDAY: 'Среда',
	Wednesday: 'Среда',
	Weekly: 'Еженедельно',
	Yes: 'Да',
	Yesterday: 'Вчера'
};
