export const tr = {
	UnauthorizeLoginError: 'Bu kullanıcı yetki seviyesi ile mobil uygulama giriş yapılamaz.',
	AverageReceiptAmount: 'Ortalama Fatura Tutarı',
	SelectMall: 'Avm Seç',
	Quota: 'Kota',
	Remain: 'Kalan',
	NoQuotaFound: 'Hiçbir kota bulunamadı!',
	QuotaDate: 'Kota Tarihi',
	GiftQuotaManagement: 'Kota İşlemleri',
	NoQuotaFounded: 'Hiçbir kota bulunamadı!',
	Save: 'Kaydet',
	PerMember: 'Kişi Başı',
	PerGlobal: 'Genel',
	None: 'Tanımsız',
	Daily: 'Günlük',
	Weekly: 'Haftalık',
	Monthly: 'Aylık',
	OnePeriod: 'Tek Dönem',
	ManageQuotas: 'Kotaları Yönet',
	TodayDeliverable: 'Bugün Verilebilir',
	CampaignsLoading: 'Kampanyalar yükleniyor...',
	AllTime: 'Tüm Zamanlar',
	ReportValuePyramid: 'Müşteri Değer Piramidi',
	people: 'kişi',
	NumberOfVisits: 'Ziyaret Sayısı',
	VisitFrequency: 'Ziyaret Frekansı',
	VİSİTFREQUENCY: 'Ziyaret Frekansı',
	VISITFREQUENCY: 'Ziyaret Frekansı',
	District: 'Semt/Mahalle',
	DİSTRİCT: 'Semt/Mahalle',
	DISTRICT: 'Semt/Mahalle',
	TotalNumberOfReceipts: 'Fatura Sayısı',
	Sector: 'Sektör',
	SECTOR: 'Sektörler',
	NumberOfShoppers: 'İşlem Yaptıran Üye Sayısı',
	NumberOfReceiptPerMember: 'Kişi Başı Fatura Sayısı',
	NumberOfVisitPerMember: 'Kişi Başı Ziyaret Sayısı',
	NumberOfDifferentStore: 'Farklı Mağaza Sayısı',
	'ShopNumberOfMember(First5)': 'Mağaza Müşteri Sayısı (İlk 5)',
	'TotalCountySpending(First5)': 'İlçe Toplam Harcama (İlk 5)',
	'DistrictTotalSpending(First5)': 'Semt Toplam Harcama (İlk 5)',
	'ShopTotalSpending(First5)': 'Mağaza Toplam Harcama (İlk 5)',
	NoCampaignFounded: 'Hiçbir kampanya bulunamadı!',
	AverageSpendingPerMember: 'Kişi Başı Ortalama Harcama',
	CampaignsLoadingTryAgainLater: 'Kampanyalar yükleniyor, daha sonra tekrar deneyin!',
	LoadingCampaigns: 'Kampanyalar yükleniyor!',
	Top3CountiesByTheTotalSpendingAmount: 'En Çok Harcama Yapılan 5 İlçe',
	Top3StoresByTheTotalReceiptAmount: 'En Çok Harcama Yapılan 3 Mağaza',
	Top3StoresByTheTotalReceiptCount: 'En Çok Faturası Olan 3 Mağaza',
	TryAgain: 'Tekrar Dene',
	LAST3MONTH: 'SON 3 AY',
	LAST6MONTH: 'SON 6 AY',
	LAST12MONTH: 'SON 12 AY',
	ALLTIME: 'TÜM ZAMANLAR',
	TotalNumberOfCustomers: 'Üye Sayıları',
	TotalNumberOfMember: 'Toplam Üye Sayısı',
	TotalNumberOfMaleMember: 'Toplam Erkek Sayısı',
	TotalNumberOfFemaleMember: 'Toplam Kadın Sayısı',
	ManagerSummary: 'Yönetici Özet',
	Quantity: 'adet',
	Person: 'kişi',
	person: 'kişi',
	ReceiptAmounts: 'Fatura Tutarı',
	MemberActivityInfo: 'Üye Aktiflik Durumu',
	ProcessedMemberInLast3Months: 'Son 3 Ayda İşlem Yaptıran Üye Sayısı ',
	ProcessedMemberInLast6Months: 'Son 6 Ayda İşlem Yaptıran Üye Sayısı ',
	ProcessedMemberInLast12Months: 'Son 12 Ayda İşlem Yaptıran Üye Sayısı ',
	NotProcessedMemberInLast12Months: 'Son 12 Aydır İşlem Yaptırmayan Üye Sayısı ',
	IsStockAreSubstracted: 'stok çıkarılsın mı?',
	IsGiftMadePassive: 'Hediye pasife alınsın mı?',
	IsGiftMadeActive: 'Hediye aktife alınsın mı?',
	MakePassive: 'Pasif yap',
	MakeActive: 'Aktif yap',
	IsStockAreAdded: 'stok eklensin mi?',
	AnErrorOccuredPleaseTryAgainLater: 'Bir hata oluştu daha sonra tekrar deneyiniz!',
	SubStock: 'Stok Çıkar',
	Sub: 'Çıkar',
	Deactivate: 'Pasifleştir',
	Activate: 'Aktifleştir',
	Add: 'Ekle',
	AddStock: 'Stok Ekle',
	GiftProgress: 'Hediye İşlemleri',
	StockValue: 'Stok Değeri',
	AreYouSure: 'Emin misiniz?',
	CantBeEmpty: 'Stok değeri boş olamaz!',
	Yes: 'Evet',
	No: 'Hayır',
	Username: 'Kullanıcı Adı',
	Password: 'Parola',
	MallCode: 'Avm Kodu',
	Login: 'Giriş',
	LogOff: 'Oturumu Kapat',
	AreYouSureWantToLogOff: 'Oturumu kapatmak istediğinize emin misiniz?',
	RememberMe: 'Beni Hatırla',
	Ok: 'Tamam',
	OK: 'Tamam',
	CANCEL: 'Vazgeç',
	Cancel: 'Vazgeç',
	CampaignDetails: 'Kampanya Detay',
	GetEMailReport: 'E-Mail Rapor İste',
	Cockpit: 'Kokpit',
	NumberOfNewMembers: 'Yeni Müşteri Sayısı',
	NumberOfShoppers: 'İşlem Yaptıran Müşteri Sayısı',
	NumberOfReceipts: 'İşletilen Fatura Sayısı',
	TotalRecordedReceiptAmount: 'İşletilen Faturaların Toplam Tutarı',
	NumberOfCoupons: 'Kupon Adedi',
	NumberOfMembersWithCoupon: 'Kupon Alan Müşteri Sayısı',
	StartDate: 'Başlangıç Tarihi',
	EndDate: 'Bitiş Tarihi',
	ReceipentEMails: 'E-Posta Adresleri',
	CompareReceipentEMails: 'E-Posta Adresleri',
	GetReport: 'Rapor Al',
	InputFieldEmptyError: 'Zorunlu alanları doldurduktan sonra yeniden deneyin.',
	InputFieldIncorrectError: 'Kullanıcı adı veya şifre hatalı.',
	MultipleLoginError:
		'Başka bir cihazda oturum açtınız. Lütfen önce ilgili oturumu kapatın. İletişim: info@omegabigdata.com',
	Error: 'Hata',
	Warning: 'Uyarı',
	Success: 'İşleminiz Başarılı',
	TakeRequest: 'Talebiniz alınmıştır. En kısa sürede raporunuz gönderilecektir.',
	InvalidMailAdress: 'Geçersiz mail adresi.\nMail adreslerinizi kontrol edip tekrar deneyin.',
	InvalidMailAdressInThere: 'Geçersiz e-posta adresi/adresleri',
	MailAdressNotNull: 'E-Posta adresi boş olamaz',
	TotalSpending: 'Toplam Harcama',
	TotalNumberOfPeople: 'Toplam Kişi Sayısı',
	AverageSpending: 'Ortalama Harcama',
	PercentOfMember: 'Kişi Yüzdesi',
	PercentOfAmount: 'Tutar Yüzdesi',
	NumberOfReceipt: 'Fatura Sayısı',
	PercentOfSpending: 'Harcama Yüzdesi',
	AverageReceiptSpending: 'Fatura Ortalama Tutar',
	AverageAmountOfReceipt: 'Fatura Ortalama Tutar',
	SortCriteria: 'Sıralama Kriter',
	StoreName: 'Mağaza Adı',
	BestOf: 'En İyiler',
	STORE: 'Mağazalar',
	GENDER: 'Cinsiyet',
	AGEINTERVAL: 'Yaş Aralığı',
	CITY: 'Şehirler',
	CİTY: 'Şehirler',
	City: 'Şehir',
	AgeInterval: 'Yaş Aralığı',
	County: 'İlçe',
	Hour: 'Saat',
	Minute: 'Dakika',
	COUNTY: 'İlçeler',
	HOUR: 'Saatler',
	DAY: 'Günler',
	Male: 'Erkek',
	MALE: 'Erkek',
	Female: 'Kadın',
	FEMALE: 'Kadın',
	Gender: 'Cinsiyet',
	StartDateBigerThanEndDateError: 'Başlangıç tarihi bitiş tarihinden büyük olamaz.',
	ServiceError: 'Sistemde bir hata oluştu. Daha sonra tekrar deneyiniz.',
	TotalNumberOfMembers: 'Toplam Müşteri Sayısı',
	ReceiptAmountPerMember: 'Kişi Başı Harcama',
	TotalNumberOfRevokedCoupons: 'Geçersiz Kupon Adedi',
	NumberOfMembers: 'Kupon Alan Kişi Sayısı',
	TotalReceiptAmountPerMember: 'Kişi Başı Harcama',
	Monday: 'Pazartesi',
	Tuesday: 'Salı',
	Wednesday: 'Çarşamba',
	Thursday: 'Perşembe',
	Friday: 'Cuma',
	Saturday: 'Cumartesi',
	Sunday: 'Pazar',
	Mon: 'Pzt',
	Tue: 'Sal',
	Wed: 'Çrş',
	Thu: 'Prş',
	Fri: 'Cum',
	Sat: 'Cts',
	Sun: 'Paz',
	Day: 'Gün',
	NoRecordedAtSpecifiedDates: 'Belirtilen tarih aralığında kayıt bulunamamıştır!',
	ServiceUnreachableError: 'Omega Big Data sunucularına ulaşılamıyor. Bağlantınızı kontrol edip yeniden deneyin.',
	ReportsDateInterval: 'Rapor Tarih Aralığı',
	DatesIncludeReports: 'Başlangıç ve bitiş tarihleri raporlara dahil edilir.',
	Filter: 'Filtrele',
	LogOffSession: 'Oturumu Kapat',
	CampaignDates: 'Kampanya Tarihleri',
	Data: ' Günü Verileri',
	DateSelection: ' Tarih Seçimi',
	SelectedDate: 'Seçili Gün',
	Yesterday: 'Dün',
	LastWeek: 'Geçen Hafta',
	LastMonth: 'Geçen Ay',
	PreviousDay: 'Bir Önceki Gün',
	Live: 'Canlı',
	SelectDate: 'Tarih Seç',
	LIVE: 'CANLI',
	InReportDates: 'Rapor Tarihlerinde',
	InCampaignDates: 'Kampanya Boyunca',
	Selection: 'Sıralama Kriter',
	Processing: 'İşlem yapılıyor...',
	'ContactUsinfo@omegabigdata.com': 'Parola yenilemek için bizimle iletişime geçin.\n\ninfo@omegabigdata.com',
	ForgotPassword: 'Parolamı unuttum',
	PasswordRenew: 'Parola Yenileme',
	ActualStock: 'Güncel Stok',
	TodayGivenStock: 'Bugün Verilen',
	TotalGivenStock: 'Toplam Verilen',
	Passive: 'Pasif',
	NoRecorded: 'Aktif kampanya bulunamadı!',
	NoGiftAtSpecifiedCampaign: 'Seçili kampanyada hediye bulunamamıştır!',
	GiftStock: 'Hediye Stok',
	CompareMethod: 'Kıyaslama Metodu',
	CompareCampaign: 'Kampanya Kıyaslama',
	CompareDate: 'Tarih Kıyaslama',
	FirstCampaign: 'Birinci Kampanya',
	SecondCampaign: 'İkinci Kampanya',
	Compare: 'Kıyasla',
	GetExcelReport: 'Excel Raporu Al',
	FirstPeriodStartDate: 'İlk Dönem Başlangıç Tarihi',
	FirstPeriodEndDate: 'İlk Dönem Bitiş Tarihi',
	SecondPeriodStartDate: 'İkinci Dönem Başlangıç Tarihi',
	SecondPeriodEndDate: 'İkinci Dönem Bitiş Tarihi',
	GeneralSummary: 'Genel Özet',
	TotalCouponNumber: 'Toplam Kupon Sayısı',
	PercentOfMale: 'Erkek Yüzde',
	PercentOfFemale: 'Kadın Yüzde',
	NumberOfNewMember: 'Yeni Üye Sayısı',
	RecordedTotalSpending: 'Kaydedilen Toplam Harcama',
	FirstPeriod: 'Dönem 1',
	SecondPeriod: 'Dönem 2',
	InvalidDateIntervalOrCampaigns: 'Hatalı tarih aralığı veya kampanya girdiniz!'
};
